FROM osrf/ros:humble-desktop
ENV ROS_DISTRO=humble
WORKDIR /ros_ws
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-colcon-common-extensions \
    ros-${ROS_DISTRO}-rclpy \
    ros-${ROS_DISTRO}-geometry-msgs \
    && rm -rf /var/lib/apt/lists/*
COPY src ./src
RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build --packages-select pubsub_demo"
CMD ["/bin/bash","-c","source /opt/ros/${ROS_DISTRO}/setup.bash && source install/setup.bash && ros2 launch pubsub_demo pubsub_launch.py"]